// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NpAwFvKy3Vnp9sPTfLG9iuDrsbowXtI',
    appId: '1:50778628971:web:ed3e0d0678326c7cc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    authDomain: 'my-cool-project-1202202.firebaseapp.com',
    databaseURL: 'https://my-cool-project-1202202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfvFXOEslHW8Bas6DEqPTQEp-uuXUcww',
    appId: '1:342657726836:android:25874b0d74c3511d575421',
    messagingSenderId: '342657726836',
    projectId: 'cosmos-by-me',
    storageBucket: 'cosmos-by-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlm2O1vMdn2z60a9lWfOrOHD_ZhUDGBzo',
    appId: '1:342657726836:ios:f0d933c6a8a9e142575421',
    messagingSenderId: '342657726836',
    projectId: 'cosmos-by-me',
    storageBucket: 'cosmos-by-me.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDML1RmFCgtz4n3Rk5VGVN1z7S_Jl14FBU',
    appId: '1:50778628971:ios:060107cb891f232dc8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    databaseURL: 'https://my-cool-project-1202202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NpAwFvKy3Vnp9sPTfLG9iuDrsbowXtI',
    appId: '1:50778628971:web:1ba4447219235888c8a22e',
    messagingSenderId: '50778628971',
    projectId: 'my-cool-project-1202202',
    authDomain: 'my-cool-project-1202202.firebaseapp.com',
    databaseURL: 'https://my-cool-project-1202202-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-cool-project-1202202.firebasestorage.app',
  );

}